"""empty message

Revision ID: 641b6dfe0bd4
Revises: d462e395dd90
Create Date: 2020-02-20 00:17:49.448646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641b6dfe0bd4'
down_revision = 'd462e395dd90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_artist_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_artist_id_fkey', 'Show', 'Show', ['artist_id'], ['id'])
    # ### end Alembic commands ###
